In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../data/raw/projects_workana.json")

In [3]:
df.tail()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
347,Adaptación de Identidad Visual y Configuración...,Se busca un profesional para realizar ajustes ...,NaN,50.0,fixed_price,"[WordPress, CSS, HTML, JavaScript, Content Man...",Programación y Tecnología,Wordpress,Instalación/Configuración de empaquetado,https://www.workana.com/job/adaptacion-de-iden...,Workana
348,Desarrollo e Implementación de Sistema de Resp...,Se busca un profesional o equipo para desarrol...,500.0,1000.0,fixed_price,"[Chatbot, Natural Language Processing, Python,...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/desarrollo-e-imple...,Workana
349,Auditoría Integral de Seguridad y Calidad de C...,Una prestigiosa empresa de movilización en Ecu...,1000.0,3000.0,fixed_price,[Dart],Programación y Tecnología,"Programación de Apps. Android, iOS y otros",Crear una aplicación nueva,https://www.workana.com/job/auditoria-integral...,Workana
350,Configuración y Capacitación para Impresión Au...,Se requiere un profesional para configurar un ...,50.0,100.0,fixed_price,"[Technical Support, System Analysis, Database,...",Programación y Tecnología,Aplicaciones de escritorio,Cambio mediano,https://www.workana.com/job/configuracion-y-ca...,Workana
351,Creación de Sitio Web en Wordpress con Enfoque...,Busco un profesional o agencia con experiencia...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS]",Programación y Tecnología,Wordpress,Desarrollo de sitio personalizado,https://www.workana.com/job/creacion-de-sitio-...,Workana

In [4]:
df.loc[df['budget_max'].isna() & (df['budget_type'] == 'fixed_price')].head()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
9,Profesional de Ti con Experiencia Integral par...,Estamos buscando un profesional de TI altament...,3000.0,NaN,fixed_price,"[Technical Support, System Analysis, Software ...",Programación y Tecnología,Otros,NaN,https://www.workana.com/job/profesional-de-ti-...,Workana
11,Desarrollo de Power App para Gestión de Pedido...,Se requiere el desarrollo de una Power App per...,3000.0,NaN,fixed_price,"[Microsoft PowerApps, Database, API, CRM]",Programación y Tecnología,Aplicaciones de escritorio,Crear una aplicación nueva,https://www.workana.com/job/desarrollo-de-powe...,Workana
40,Desarrollo Full-Stack de Sistema de Salud Digi...,Se busca un desarrollador o equipo full-stack ...,3000.0,NaN,fixed_price,"[Android, iOS, JavaScript, HTML, CSS, Database...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/desarrollo-full-st...,Workana
53,Desarrollo de Aplicación Móvil Saas Multiplata...,Se busca un desarrollador o equipo para crear ...,3000.0,NaN,fixed_price,"[Flutter, React Native, Android, iOS, Database...",Programación y Tecnología,"Programación de Apps. Android, iOS y otros",Crear una aplicación nueva,https://www.workana.com/job/desarrollo-de-apli...,Workana
72,Desarrollo y Estrategia de E-commerce para Pro...,Se busca un profesional o equipo para desarrol...,3000.0,NaN,fixed_price,"[WooCommerce, Shopify, Magento, PHP, MySQL, HT...",Programación y Tecnología,Tiendas Online (e-commerce),Crear una tienda nueva,https://www.workana.com/job/desarrollo-y-estra...,Workana

In [5]:
print(df.loc[df['budget_max'].isna() & (df['budget_type'] == 'fixed_price')].shape[0])

25

In [6]:
df.loc[df['budget_max'].isna() & (df['budget_type'] == 'hourly')].head()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
38,Soporte Técnico Especializado en Shopify para ...,Busco un soporte técnico freelance para el rel...,45.0,NaN,hourly,"[Shopify, HTML, CSS, JavaScript, Tiendas Onlin...",Programación y Tecnología,Tiendas Online (e-commerce),Crear una tienda nueva,https://www.workana.com/job/soporte-tecnico-es...,Workana
59,Experto en Automatización e Implementación de ...,Buscamos un profesional con experiencia en aut...,45.0,NaN,hourly,"[Machine Learning, Python, Scripts & Utilities]",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/experto-en-automat...,Workana
74,Estrategia Integral para Escalar y Rentabiliza...,Busco un profesional con experiencia en e-comm...,45.0,NaN,hourly,"[Shopify, WooCommerce, PrestaShop, Magento, PH...",Programación y Tecnología,Tiendas Online (e-commerce),Crear una tienda nueva,https://www.workana.com/job/estrategia-integra...,Workana
84,Migración Técnica de Wpbakery a Gutenberg en W...,Hola. Busco un desarrollador WordPress/WooComm...,45.0,NaN,hourly,"[WordPress, PHP, MySQL, HTML, CSS, JavaScript,...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/migracion-tecnica-...,Workana
97,Desarrollo de Aplicación Móvil Nativa para Sis...,Se busca un equipo o desarrollador con experie...,45.0,NaN,hourly,"[Android, iOS, Java, Kotlin, Swift, API, REST ...",Programación y Tecnología,"Programación de Apps. Android, iOS y otros",Crear una aplicación nueva,https://www.workana.com/job/desarrollo-de-apli...,Workana

In [7]:
print(df.loc[df['budget_max'].isna() & (df['budget_type'] == 'hourly')].shape[0])

14

In [8]:
df.loc[df['budget_min'].isna() & (df['budget_type'] == 'fixed_price')].head()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
68,Desarrollo de Juego de Terror 3d en Unity para...,Se busca un desarrollador de juegos experiment...,NaN,50.0,fixed_price,"[Unity 3D, Desarrollo de video juegos, Program...",Programación y Tecnología,Aplicaciones de escritorio,Crear una aplicación nueva,https://www.workana.com/job/desarrollo-de-jueg...,Workana
90,Ingeniero de Sistemas para Modificación de Res...,Se busca un ingeniero en sistemas con experien...,NaN,50.0,fixed_price,"[Informática, Database, SQL, PHP, MySQL, Syste...",Programación y Tecnología,Programación Web,Cambio mediano,https://www.workana.com/job/ingeniero-de-siste...,Workana
133,Desarrollo de Plataforma Web para Venta de Cla...,Se requiere el desarrollo de una página web co...,NaN,50.0,fixed_price,"[HTML, CSS, JavaScript, PHP, MySQL, WordPress,...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/desarrollo-de-plat...,Workana
154,Godot Implementación de Mecánica de Bate con F...,Se busca un desarrollador para implementar una...,NaN,50.0,fixed_price,"[Desarrollo de video juegos, Programación de v...",Programación y Tecnología,Aplicaciones de escritorio,Cambio mediano,https://www.workana.com/job/implementacion-de-...,Workana
182,Análisis Exhaustivo y Sugerencias de Mejora pa...,Se busca un profesional para realizar un análi...,NaN,50.0,fixed_price,"[Testing, QA, System Analysis, HTML, CSS, Java...",Programación y Tecnología,Programación Web,Bug o cambio pequeño,https://www.workana.com/job/analisis-exhaustiv...,Workana

In [9]:
df.loc[df['budget_min'].isna() & (df['budget_type'] == 'fixed_price')].shape[0]

13

In [10]:
df.loc[df['budget_min'].isna() & (df['budget_type'] == 'hourly')].head()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
4,Especialista Itil para Diseño e Implementación...,Actualmente me desempeño como Jefe de Servicio...,NaN,15.0,hourly,"[Informática, Technical Support, System Analys...",Programación y Tecnología,Otros,NaN,https://www.workana.com/job/especialista-itil-...,Workana
22,Ingeniero Qa Senior para Aplicación Social Móv...,YOIN es una aplicación social/de comunidad (iO...,NaN,15.0,hourly,"[QA, Android, iOS, Flutter, Python, Flask, Pos...",Programación y Tecnología,"Programación de Apps. Android, iOS y otros",Crear una aplicación nueva,https://www.workana.com/job/ingeniero-qa-senio...,Workana
30,Consultor Freelancer Senior en Business Intell...,Buscamos un consultor freelance de habla hispa...,NaN,15.0,hourly,"[Extract Transform Load (ETL), Tableau, SQL, C...",Programación y Tecnología,Data Science,NaN,https://www.workana.com/job/consultor-freelanc...,Workana
69,Desarrollo de Sistema Web para Búsqueda y Encu...,Se requiere el desarrollo de un sistema web co...,NaN,15.0,hourly,"[PHP, JavaScript, HTML, CSS, MySQL, React.js, ...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/desarrollo-de-sist...,Workana
76,Desarrollo de Página Web Informativa en Php,Se busca un desarrollador web para la creación...,NaN,15.0,hourly,"[PHP, HTML, CSS, JavaScript, MySQL]",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/desarrollo-de-pagi...,Workana

In [11]:
df.loc[df['budget_min'].isna() & (df['budget_type'] == 'hourly')].shape[0]

13

In [12]:
df.loc[df['budget_min'].isna()].shape[0]

26

In [13]:
df.loc[df['category'].isna()]

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
115,Gestionar redes sociales y campaña de publici...,Buscamos personas sepa gestionar redes social...,50.0,100.0,fixed_price,[API],NaN,NaN,NaN,https://www.workana.com/job/gestionar-redes-so...,Workana

In [14]:
df.loc[df['scope_project'].isna()]

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
4,Especialista Itil para Diseño e Implementación...,Actualmente me desempeño como Jefe de Servicio...,NaN,15.0,hourly,"[Informática, Technical Support, System Analys...",Programación y Tecnología,Otros,NaN,https://www.workana.com/job/especialista-itil-...,Workana
6,Experto Senior en Automatización Avanzada de K...,Buscamos un experto senior en automatización d...,250.0,500.0,fixed_price,"[CRM, API, Machine Learning, Chatbot, Python, ...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/experto-senior-en-...,Workana
8,Desarrollo de Chatbot con Inteligencia Artific...,Se busca un desarrollador o equipo con experie...,1000.0,3000.0,fixed_price,"[Chatbot, API, Python, Machine Learning, Natur...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/desarrollo-de-chat...,Workana
9,Profesional de Ti con Experiencia Integral par...,Estamos buscando un profesional de TI altament...,3000.0,NaN,fixed_price,"[Technical Support, System Analysis, Software ...",Programación y Tecnología,Otros,NaN,https://www.workana.com/job/profesional-de-ti-...,Workana
15,Experto en N8n y Agentes Ia para Desarrollo de...,Estamos desarrollando una plataforma de formac...,250.0,500.0,fixed_price,"[API, Python, JavaScript, Node.js, Web Service...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/experto-en-n8n-y-a...,Workana
...,...,...,...,...,...,...,...,...,...,...,...
331,Desarrollo de Chatbot para Whatsapp y Gestión ...,Se busca un profesional o equipo para desarrol...,3000.0,NaN,fixed_price,"[Chatbot, API, HTML, CSS, JavaScript, Python, ...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/desarrollo-de-chat...,Workana
341,Desarrollo e Implementación de Chatbot con Ia ...,Se busca un desarrollador o equipo con experie...,1000.0,3000.0,fixed_price,"[Machine Learning, Natural Language Processing...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/desarrollo-e-imple...,Workana
343,Desarrollo de Generador de Modelos 3d con Ia a...,Se busca un desarrollador o equipo con experie...,1000.0,3000.0,fixed_price,"[Machine Learning, Python, Computer Graphics, ...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/desarrollo-de-gene...,Workana
344,Profesional Experto en Power Bi para Migración...,Buscamos un(a) profesional con experiencia com...,15.0,45.0,hourly,"[Power BI, Modelado de Datos, Data Warehousing...",Programación y Tecnología,Data Science,NaN,https://www.workana.com/job/profesional-expert...,Workana
348,Desarrollo e Implementación de Sistema de Resp...,Se busca un profesional o equipo para desarrol...,500.0,1000.0,fixed_price,"[Chatbot, Natural Language Processing, Python,...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/desarrollo-e-imple...,Workana

In [15]:
df['title'].value_counts()

title
Automatización de Facturas con Ocr, Zapier e Integración Sql Erp Sade para Despacho Contable     2
Implementador de Crm/Whatsapp Api con Automatizaciones Comerciales                               1
Desarrollador Node.js / Sqlite para Proyecto Corto de Api Backend                                1
Desarrollador Wordpress + Elementor Pro para Landing Responsive + Whatsapp (Solo experiencia)    1
Especialista Itil para Diseño e Implementación de Plan de Comunicación en Servicios Ti           1
                                                                                                ..
Adaptación de Identidad Visual y Configuración de Wordpress con Tutor Lms                        1
Desarrollo e Implementación de Sistema de Respuestas Automáticas con Ia para Whatsapp            1
Auditoría Integral de Seguridad y Calidad de Código                                              1
Configuración y Capacitación para Impresión Autónoma de Etiquetas con Códigos de Barras          1
Creación de Sitio Web en Wordpress con Enfoque en Captación de Clientes y Conversión             1
Name: count, Length: 351, dtype: int64

In [16]:
df.loc[df['title'] == 'Automatización de Facturas con Ocr, Zapier e Integración Sql Erp Sade para Despacho Contable', 'project_url'].value_counts()

project_url
https://www.workana.com/job/automatizacion-de-facturas-con-ocr-zapier-e-integracion-sql-erp-sade-para-despacho-contable    2
Name: count, dtype: int64

In [17]:
df.loc[df['title'] == 'Automatización de Facturas con Ocr, Zapier e Integración Sql Erp Sade para Despacho Contable']

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
1,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/automatizacion-de-...,Workana
41,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/automatizacion-de-...,Workana

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          352 non-null    str
 1   description    352 non-null    str
 2   budget_min     326 non-null    float64
 3   budget_max     313 non-null    float64
 4   budget_type    352 non-null    str
 5   skills         352 non-null    object
 6   category       351 non-null    str
 7   subcategory    351 non-null    str
 8   scope_project  275 non-null    str
 9   project_url    352 non-null    str
 10  platform       352 non-null    str
dtypes: float64(2), object(1), str(8)
memory usage: 30.4+ KB

In [19]:
df.describe()

        budget_min   budget_max
count   326.000000   313.000000
mean    722.806748  1417.284345
std     765.910432  1291.954073
min      15.000000    15.000000
25%     100.000000   250.000000
50%     500.000000  1000.000000
75%    1000.000000  3000.000000
max    3000.000000  3000.000000

In [20]:
df.isna().sum()

title             0
description       0
budget_min       26
budget_max       39
budget_type       0
skills            0
category          1
subcategory       1
scope_project    77
project_url       0
platform          0
dtype: int64

In [21]:
df.loc[df["project_url"].duplicated()]

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
41,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/automatizacion-de-...,Workana

In [22]:
df['budget_type'].value_counts()

budget_type
fixed_price    308
hourly          44
Name: count, dtype: int64

In [23]:
df["skills"].apply(len).describe()

count    352.000000
mean       7.193182
std        3.138250
min        1.000000
25%        5.000000
50%        7.000000
75%        9.000000
max       23.000000
Name: skills, dtype: float64

In [24]:
df.loc[df["skills"].apply(len) == 1].shape[0]

3

In [25]:
df.loc[df["skills"].apply(len) == 23].shape[0]

1

In [26]:
print("Rows:", len(df))
print("Unique URLs:", df['project_url'].nunique())
print("Duplicate URLs:", df['project_url'].duplicated().sum())

print(f"\n{df["budget_type"].value_counts()}")

print("\nMissing Values")
print(df.isna().sum())

Rows: 352
Unique URLs: 351
Duplicate URLs: 1

budget_type
fixed_price    308
hourly          44
Name: count, dtype: int64

Missing Values
title             0
description       0
budget_min       26
budget_max       39
budget_type       0
skills            0
category          1
subcategory       1
scope_project    77
project_url       0
platform          0
dtype: int64

In [27]:
df['subcategory'].value_counts()

subcategory
Programación Web                              158
Inteligencia Artificial                        50
Tiendas Online (e-commerce)                    47
Programación de Apps. Android, iOS y otros     40
Aplicaciones de escritorio                     19
Otros                                          16
Wordpress                                      10
Data Science                                    9
Diseño Web                                      2
Name: count, dtype: int64

In [28]:
df['category'].value_counts()

category
Programación y Tecnología    351
Name: count, dtype: int64

In [29]:
df

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,scope_project,project_url,platform
0,Implementador de Crm/Whatsapp Api con Automati...,Se busca un implementador freelance con experi...,250.0,500.0,fixed_price,"[CRM, API, Facebook, Scripts & Utilities, Data...",Programación y Tecnología,Tiendas Online (e-commerce),Crear una tienda nueva,https://www.workana.com/job/implementador-de-c...,Workana
1,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/automatizacion-de-...,Workana
2,Desarrollador Node.js / Sqlite para Proyecto C...,Buscamos un programador backend con perfil Jun...,100.0,250.0,fixed_price,"[Node.js, Express.js, SQL, Database, API]",Programación y Tecnología,Programación Web,Cambio mediano,https://www.workana.com/job/desarrollador-node...,Workana
3,Desarrollador Wordpress + Elementor Pro para L...,Busco desarrollador con experiencia comprobabl...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS, Responsive Web Design]",Programación y Tecnología,Programación Web,Crear un nuevo sitio personalizado,https://www.workana.com/job/desarrollador-word...,Workana
4,Especialista Itil para Diseño e Implementación...,Actualmente me desempeño como Jefe de Servicio...,NaN,15.0,hourly,"[Informática, Technical Support, System Analys...",Programación y Tecnología,Otros,NaN,https://www.workana.com/job/especialista-itil-...,Workana
...,...,...,...,...,...,...,...,...,...,...,...
347,Adaptación de Identidad Visual y Configuración...,Se busca un profesional para realizar ajustes ...,NaN,50.0,fixed_price,"[WordPress, CSS, HTML, JavaScript, Content Man...",Programación y Tecnología,Wordpress,Instalación/Configuración de empaquetado,https://www.workana.com/job/adaptacion-de-iden...,Workana
348,Desarrollo e Implementación de Sistema de Resp...,Se busca un profesional o equipo para desarrol...,500.0,1000.0,fixed_price,"[Chatbot, Natural Language Processing, Python,...",Programación y Tecnología,Inteligencia Artificial,NaN,https://www.workana.com/job/desarrollo-e-imple...,Workana
349,Auditoría Integral de Seguridad y Calidad de C...,Una prestigiosa empresa de movilización en Ecu...,1000.0,3000.0,fixed_price,[Dart],Programación y Tecnología,"Programación de Apps. Android, iOS y otros",Crear una aplicación nueva,https://www.workana.com/job/auditoria-integral...,Workana
350,Configuración y Capacitación para Impresión Au...,Se requiere un profesional para configurar un ...,50.0,100.0,fixed_price,"[Technical Support, System Analysis, Database,...",Programación y Tecnología,Aplicaciones de escritorio,Cambio mediano,https://www.workana.com/job/configuracion-y-ca...,Workana
351,Creación de Sitio Web en Wordpress con Enfoque...,Busco un profesional o agencia con experiencia...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS]",Programación y Tecnología,Wordpress,Desarrollo de sitio personalizado,https://www.workana.com/job/creacion-de-sitio-...,Workana

In [36]:
df.loc[df['project_url'].duplicated(),'project_url']

41    https://www.workana.com/job/automatizacion-de-...
Name: project_url, dtype: str

In [37]:
df = df.drop_duplicates(subset=['project_url'], keep='first')

In [38]:
df.loc[df['project_url'].duplicated(),'project_url']

Series([], Name: project_url, dtype: str)

In [39]:
df = df.drop('scope_project', axis=1)

In [40]:
df

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform
0,Implementador de Crm/Whatsapp Api con Automati...,Se busca un implementador freelance con experi...,250.0,500.0,fixed_price,"[CRM, API, Facebook, Scripts & Utilities, Data...",Programación y Tecnología,Tiendas Online (e-commerce),https://www.workana.com/job/implementador-de-c...,Workana
1,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,https://www.workana.com/job/automatizacion-de-...,Workana
2,Desarrollador Node.js / Sqlite para Proyecto C...,Buscamos un programador backend con perfil Jun...,100.0,250.0,fixed_price,"[Node.js, Express.js, SQL, Database, API]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-node...,Workana
3,Desarrollador Wordpress + Elementor Pro para L...,Busco desarrollador con experiencia comprobabl...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS, Responsive Web Design]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-word...,Workana
4,Especialista Itil para Diseño e Implementación...,Actualmente me desempeño como Jefe de Servicio...,NaN,15.0,hourly,"[Informática, Technical Support, System Analys...",Programación y Tecnología,Otros,https://www.workana.com/job/especialista-itil-...,Workana
...,...,...,...,...,...,...,...,...,...,...
347,Adaptación de Identidad Visual y Configuración...,Se busca un profesional para realizar ajustes ...,NaN,50.0,fixed_price,"[WordPress, CSS, HTML, JavaScript, Content Man...",Programación y Tecnología,Wordpress,https://www.workana.com/job/adaptacion-de-iden...,Workana
348,Desarrollo e Implementación de Sistema de Resp...,Se busca un profesional o equipo para desarrol...,500.0,1000.0,fixed_price,"[Chatbot, Natural Language Processing, Python,...",Programación y Tecnología,Inteligencia Artificial,https://www.workana.com/job/desarrollo-e-imple...,Workana
349,Auditoría Integral de Seguridad y Calidad de C...,Una prestigiosa empresa de movilización en Ecu...,1000.0,3000.0,fixed_price,[Dart],Programación y Tecnología,"Programación de Apps. Android, iOS y otros",https://www.workana.com/job/auditoria-integral...,Workana
350,Configuración y Capacitación para Impresión Au...,Se requiere un profesional para configurar un ...,50.0,100.0,fixed_price,"[Technical Support, System Analysis, Database,...",Programación y Tecnología,Aplicaciones de escritorio,https://www.workana.com/job/configuracion-y-ca...,Workana
351,Creación de Sitio Web en Wordpress con Enfoque...,Busco un profesional o agencia con experiencia...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS]",Programación y Tecnología,Wordpress,https://www.workana.com/job/creacion-de-sitio-...,Workana

In [41]:
df['currency'] = 'USD'

In [42]:
df

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
0,Implementador de Crm/Whatsapp Api con Automati...,Se busca un implementador freelance con experi...,250.0,500.0,fixed_price,"[CRM, API, Facebook, Scripts & Utilities, Data...",Programación y Tecnología,Tiendas Online (e-commerce),https://www.workana.com/job/implementador-de-c...,Workana,USD
1,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,https://www.workana.com/job/automatizacion-de-...,Workana,USD
2,Desarrollador Node.js / Sqlite para Proyecto C...,Buscamos un programador backend con perfil Jun...,100.0,250.0,fixed_price,"[Node.js, Express.js, SQL, Database, API]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-node...,Workana,USD
3,Desarrollador Wordpress + Elementor Pro para L...,Busco desarrollador con experiencia comprobabl...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS, Responsive Web Design]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-word...,Workana,USD
4,Especialista Itil para Diseño e Implementación...,Actualmente me desempeño como Jefe de Servicio...,NaN,15.0,hourly,"[Informática, Technical Support, System Analys...",Programación y Tecnología,Otros,https://www.workana.com/job/especialista-itil-...,Workana,USD
...,...,...,...,...,...,...,...,...,...,...,...
347,Adaptación de Identidad Visual y Configuración...,Se busca un profesional para realizar ajustes ...,NaN,50.0,fixed_price,"[WordPress, CSS, HTML, JavaScript, Content Man...",Programación y Tecnología,Wordpress,https://www.workana.com/job/adaptacion-de-iden...,Workana,USD
348,Desarrollo e Implementación de Sistema de Resp...,Se busca un profesional o equipo para desarrol...,500.0,1000.0,fixed_price,"[Chatbot, Natural Language Processing, Python,...",Programación y Tecnología,Inteligencia Artificial,https://www.workana.com/job/desarrollo-e-imple...,Workana,USD
349,Auditoría Integral de Seguridad y Calidad de C...,Una prestigiosa empresa de movilización en Ecu...,1000.0,3000.0,fixed_price,[Dart],Programación y Tecnología,"Programación de Apps. Android, iOS y otros",https://www.workana.com/job/auditoria-integral...,Workana,USD
350,Configuración y Capacitación para Impresión Au...,Se requiere un profesional para configurar un ...,50.0,100.0,fixed_price,"[Technical Support, System Analysis, Database,...",Programación y Tecnología,Aplicaciones de escritorio,https://www.workana.com/job/configuracion-y-ca...,Workana,USD
351,Creación de Sitio Web en Wordpress con Enfoque...,Busco un profesional o agencia con experiencia...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS]",Programación y Tecnología,Wordpress,https://www.workana.com/job/creacion-de-sitio-...,Workana,USD