In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../data/raw/projects_merged.jsonl", lines=True)

In [3]:
df.head()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
0,Implementador de Crm/Whatsapp Api con Automati...,Se busca un implementador freelance con experi...,250.0,500.0,fixed_price,"[CRM, API, Facebook, Scripts & Utilities, Data...",Programación y Tecnología,Tiendas Online (e-commerce),https://www.workana.com/job/implementador-de-c...,Workana,USD
1,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,https://www.workana.com/job/automatizacion-de-...,Workana,USD
2,Desarrollador Node.js / Sqlite para Proyecto C...,Buscamos un programador backend con perfil Jun...,100.0,250.0,fixed_price,"[Node.js, Express.js, SQL, Database, API]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-node...,Workana,USD
3,Desarrollador Wordpress + Elementor Pro para L...,Busco desarrollador con experiencia comprobabl...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS, Responsive Web Design]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-word...,Workana,USD
4,Especialista Itil para Diseño e Implementación...,Actualmente me desempeño como Jefe de Servicio...,NaN,15.0,hourly,"[Informática, Technical Support, System Analys...",Programación y Tecnología,Otros,https://www.workana.com/job/especialista-itil-...,Workana,USD

In [4]:
df.tail()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
4718,Hebrew Translation Quality Reviewer,I have a year-long project that needs a sharp ...,8.0,15.0,hourly,"[Machine Translation, Language Tutoring, Editi...",Artificial Intelligence,Machine Translation,https://www.freelancer.com/projects/machine-tr...,Freelancer,USD
4719,"Logo, Copywriting & AI Poster",Saya mencari seorang kreatif yang bisa mengeks...,8.0,15.0,hourly,"[Copywriting, Adobe Illustrator, Adobe Photosh...",Artificial Intelligence,Copywriting,https://www.freelancer.com/projects/copywritin...,Freelancer,USD
4720,Outdoor Ultrasonic Vehicle Detection,I need assistance in developing electronic for...,25.0,50.0,hourly,"[Object Detection, Embedded Systems, Electroni...",Artificial Intelligence,Object Detection,https://www.freelancer.com/projects/object-det...,Freelancer,USD
4721,Speech Recording Task,I need native-sounding adults (25 years or old...,100.0,400.0,hourly,"[Voice Over, Speech Synthesis, Voice Acting, A...",Artificial Intelligence,Voice Over,https://www.freelancer.com/projects/voice-over...,Freelancer,INR
4722,10 Virtual Assistants Needed,I have a heavy workload managing emails and ch...,250.0,750.0,fixed_price,"[Email Handling, Chat Operation, Virtual Assis...",Artificial Intelligence,Email Handling,https://www.freelancer.com/projects/email-hand...,Freelancer,USD

## 1. Dataset Overview

In [5]:
print(f"Total projects: {df.shape[0]}")

Total projects: 4723

In [6]:
print(f"Workana projects: {df.loc[df['platform'] == 'Workana'].shape[0]}")

Workana projects: 351

In [7]:
print(f"Freelancer projects: {df.loc[df['platform'] == 'Freelancer'].shape[0]}")

Freelancer projects: 4372

In [8]:
print(f"Percentage of Workana projects: {df.loc[df['platform'] == 'Workana'].shape[0] / df.shape[0] * 100:.2f}%")
print(f"Percentage of Freelancer projects: {df.loc[df['platform'] == 'Freelancer'].shape[0] / df.shape[0] * 100:.2f}%")

Percentage of Workana projects: 7.43%
Percentage of Freelancer projects: 92.57%

## 2. Schema Validation

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4723 entries, 0 to 4722
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        4723 non-null   str
 1   description  4723 non-null   str
 2   budget_min   4697 non-null   float64
 3   budget_max   4590 non-null   float64
 4   budget_type  4723 non-null   str
 5   skills       4723 non-null   object
 6   category     4722 non-null   str
 7   subcategory  4722 non-null   str
 8   project_url  4723 non-null   str
 9   platform     4723 non-null   str
 10  currency     4723 non-null   str
dtypes: float64(2), object(1), str(8)
memory usage: 406.0+ KB

In [10]:
df.loc[:,'skills']

0       [CRM, API, Facebook, Scripts & Utilities, Data...
1       [SQL, Database, ERP, API, System Analysis, Mod...
2               [Node.js, Express.js, SQL, Database, API]
3           [WordPress, HTML, CSS, Responsive Web Design]
4       [Informática, Technical Support, System Analys...
                              ...
4718    [Machine Translation, Language Tutoring, Editi...
4719    [Copywriting, Adobe Illustrator, Adobe Photosh...
4720    [Object Detection, Embedded Systems, Electroni...
4721    [Voice Over, Speech Synthesis, Voice Acting, A...
4722    [Email Handling, Chat Operation, Virtual Assis...
Name: skills, Length: 4723, dtype: object

In [11]:
df['platform'].isna().sum()

np.int64(0)

## 3. Missing Values

In [12]:
df.isna().sum()

title            0
description      0
budget_min      26
budget_max     133
budget_type      0
skills           0
category         1
subcategory      1
project_url      0
platform         0
currency         0
dtype: int64

In [13]:
print(f"Percentage of missing values in 'budget_min': {df['budget_min'].isna().sum() / df.shape[0] * 100:.2f}%")
print(f"Percentage of missing values in 'budget_max': {df['budget_max'].isna().sum() / df.shape[0] * 100:.2f}%")

Percentage of missing values in 'budget_min': 0.55%
Percentage of missing values in 'budget_max': 2.82%

In [14]:
df.loc[df['budget_max'].isna() | (df['budget_min'].isna()), 'platform'].value_counts()

platform
Freelancer    94
Workana       65
Name: count, dtype: int64

## 4. Duplicates

In [15]:
df['project_url'].duplicated().sum()

np.int64(0)

In [16]:
df['title'].duplicated().sum()

np.int64(186)

In [17]:
df.loc[df['title'].duplicated()]

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
358,All-in-One Travel Booking Platform,The platform will include:\n• Hotel booking\n•...,5000.0,10000.0,fixed_price,"[Flutter, .NET, AI Chatbot, API Integration, H...","Websites, IT & Software",Flutter,https://www.freelancer.com/projects/flutter/al...,Freelancer,EUR
368,C# Tally XML Integration DLL,I need a clean C# class-library (targeting .NE...,1500.0,12500.0,fixed_price,"[JSON, ERP, Software Development, Software Eng...","Websites, IT & Software",JSON,https://www.freelancer.com/projects/json/tally...,Freelancer,INR
419,Email & Instagram Marketing Boost,I’m ready to step up my customer outreach with...,12500.0,37500.0,fixed_price,"[Instagram Marketing, Mailchimp, A/B Testing, ...","Websites, IT & Software",Instagram Marketing,https://www.freelancer.com/projects/instagram-...,Freelancer,INR
439,Law Firm Website Build,I run a small legal practice and now need a we...,250.0,750.0,fixed_price,"[Web Development, WordPress, CMS, SEO, PHP, We...","Websites, IT & Software",Web Development,https://www.freelancer.com/projects/web-develo...,Freelancer,USD
440,WordPress Developer Needed for New Canadian No...,WordPress Developer Needed for New Canadian No...,1500.0,3000.0,fixed_price,"[Web Development, Accessibility, CSS, Website ...","Websites, IT & Software",Web Development,https://www.freelancer.com/projects/web-develo...,Freelancer,USD
...,...,...,...,...,...,...,...,...,...,...,...
4481,Website Redesign,The objective of this project is to completely...,1500.0,12500.0,fixed_price,"[Website Design, Graphic Design, HTML, Web Des...","Websites, IT & Software",Website Design,https://www.freelancer.com/projects/website-de...,Freelancer,INR
4570,Part-Time Online English Tutor,I’m assembling a small team for our online sum...,750.0,1500.0,fixed_price,"[Teaching/Lecturing, Education & Tutoring, Lan...","Websites, IT & Software",Teaching/Lecturing,https://www.freelancer.com/projects/teaching-l...,Freelancer,USD
4612,AI Brand Awareness Video,"I need a short, realistic-looking video create...",250.0,750.0,fixed_price,"[AI Video, Video Production, AI Content Creati...",Artificial Intelligence,AI Video,https://www.freelancer.com/projects/ai-video/b...,Freelancer,USD
4644,Bilingual AI Voice Recording Indonesia & English,Perusahaan kami sedang membuka kesempatan bagi...,10.0,30.0,fixed_price,"[AI Audio-to-audio, AI Chatbot, AI Development...",Artificial Intelligence,AI Audio-to-audio,https://www.freelancer.com/projects/ai-audio-t...,Freelancer,USD
4716,Natural HD Photo Enhancement,I have a single portrait that I want to turn i...,100.0,400.0,hourly,"[After Effects, Color Grading, Illustration, I...",Artificial Intelligence,After Effects,https://www.freelancer.com/projects/after-effe...,Freelancer,INR

In [18]:
df.loc[df['title'] == 'AI Brand Awareness Video']

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
4606,AI Brand Awareness Video,"I need a short, realistic-looking video create...",400.0,750.0,hourly,"[After Effects, AI Animation, AI Art Creation,...",Artificial Intelligence,After Effects,https://www.freelancer.com/projects/after-effe...,Freelancer,INR
4612,AI Brand Awareness Video,"I need a short, realistic-looking video create...",250.0,750.0,fixed_price,"[AI Video, Video Production, AI Content Creati...",Artificial Intelligence,AI Video,https://www.freelancer.com/projects/ai-video/b...,Freelancer,USD

In [19]:
df.loc[df['title'].duplicated(), 'platform'].value_counts()

platform
Freelancer    186
Name: count, dtype: int64

## 5. Budget Analysis

In [20]:
df['budget_type'].value_counts()

budget_type
fixed_price    3709
hourly         1014
Name: count, dtype: int64

In [21]:
df.loc[~df['budget_min'].isna() & ~df['budget_max'].isna()]

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
0,Implementador de Crm/Whatsapp Api con Automati...,Se busca un implementador freelance con experi...,250.0,500.0,fixed_price,"[CRM, API, Facebook, Scripts & Utilities, Data...",Programación y Tecnología,Tiendas Online (e-commerce),https://www.workana.com/job/implementador-de-c...,Workana,USD
1,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,https://www.workana.com/job/automatizacion-de-...,Workana,USD
2,Desarrollador Node.js / Sqlite para Proyecto C...,Buscamos un programador backend con perfil Jun...,100.0,250.0,fixed_price,"[Node.js, Express.js, SQL, Database, API]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-node...,Workana,USD
3,Desarrollador Wordpress + Elementor Pro para L...,Busco desarrollador con experiencia comprobabl...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS, Responsive Web Design]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-word...,Workana,USD
5,Desarrollo de Sistema de Automatización de Res...,Se busca un desarrollador para crear e impleme...,500.0,1000.0,fixed_price,"[Chatbot, API, Python, JavaScript]",Programación y Tecnología,"Programación de Apps. Android, iOS y otros",https://www.workana.com/job/desarrollo-de-sist...,Workana,USD
...,...,...,...,...,...,...,...,...,...,...,...
4718,Hebrew Translation Quality Reviewer,I have a year-long project that needs a sharp ...,8.0,15.0,hourly,"[Machine Translation, Language Tutoring, Editi...",Artificial Intelligence,Machine Translation,https://www.freelancer.com/projects/machine-tr...,Freelancer,USD
4719,"Logo, Copywriting & AI Poster",Saya mencari seorang kreatif yang bisa mengeks...,8.0,15.0,hourly,"[Copywriting, Adobe Illustrator, Adobe Photosh...",Artificial Intelligence,Copywriting,https://www.freelancer.com/projects/copywritin...,Freelancer,USD
4720,Outdoor Ultrasonic Vehicle Detection,I need assistance in developing electronic for...,25.0,50.0,hourly,"[Object Detection, Embedded Systems, Electroni...",Artificial Intelligence,Object Detection,https://www.freelancer.com/projects/object-det...,Freelancer,USD
4721,Speech Recording Task,I need native-sounding adults (25 years or old...,100.0,400.0,hourly,"[Voice Over, Speech Synthesis, Voice Acting, A...",Artificial Intelligence,Voice Over,https://www.freelancer.com/projects/voice-over...,Freelancer,INR
4722,10 Virtual Assistants Needed,I have a heavy workload managing emails and ch...,250.0,750.0,fixed_price,"[Email Handling, Chat Operation, Virtual Assis...",Artificial Intelligence,Email Handling,https://www.freelancer.com/projects/email-hand...,Freelancer,USD

In [22]:
print(f"Only 'budget_min': {df.loc[~df['budget_min'].isna() & df['budget_max'].isna()].shape[0]}")
print(f"Only 'budget_max': {df.loc[df['budget_min'].isna() & ~df['budget_max'].isna()].shape[0]}")

Only 'budget_min': 133
Only 'budget_max': 26

In [23]:
df.describe()

         budget_min    budget_max
count  4.697000e+03  4.590000e+03
mean   5.333829e+03  1.308841e+04
std    7.748692e+04  1.596163e+05
min    2.000000e+00  4.000000e+00
25%    3.000000e+01  1.600000e+02
50%    2.500000e+02  7.500000e+02
75%    1.500000e+03  3.000000e+03
max    5.000000e+06  1.000000e+07

## 6. Currency Analysis

In [24]:
df['currency'].value_counts()

currency
USD    2636
INR    1682
EUR     241
GBP     164
Name: count, dtype: int64

**Prices** should be normalized to USD

## 7. Platform Comparison

In [27]:
print(f"Workana projects: {df.loc[df['platform'] == 'Workana'].shape[0]}")
print(f"Freelancer projects: {df.loc[df['platform'] == 'Freelancer'].shape[0]}")

Workana projects: 351
Freelancer projects: 4372

In [36]:
print(f"Workana budget types: {df.loc[df['platform'] == 'Workana', 'budget_type'].value_counts().to_dict()}")
print(f"Freelancer budget types: {df.loc[df['platform'] == 'Freelancer', 'budget_type'].value_counts().to_dict()}")

Workana budget types: {'fixed_price': 307, 'hourly': 44}
Freelancer budget types: {'fixed_price': 3402, 'hourly': 970}

In [40]:
print(f"Workana missing values: {df.loc[df['platform'] == 'Workana'].isnull().sum().to_dict()}")
print(f"Freelancer missing values: {df.loc[df['platform'] == 'Freelancer'].isnull().sum().to_dict()}")

Workana missing values: {'title': 0, 'description': 0, 'budget_min': 26, 'budget_max': 39, 'budget_type': 0, 'skills': 0, 'category': 1, 'subcategory': 1, 'project_url': 0, 'platform': 0, 'currency': 0}
Freelancer missing values: {'title': 0, 'description': 0, 'budget_min': 0, 'budget_max': 94, 'budget_type': 0, 'skills': 0, 'category': 0, 'subcategory': 0, 'project_url': 0, 'platform': 0, 'currency': 0}

In [54]:
print("Workana skills:")
df.loc[df['platform'] == 'Workana', 'skills'].apply(len).describe()

Workana skills:

count    351.000000
mean       7.196581
std        3.142081
min        1.000000
25%        5.000000
50%        7.000000
75%        9.000000
max       23.000000
Name: skills, dtype: float64

In [55]:
print("Freelancer skills:")
df.loc[df['platform'] == 'Freelancer', 'skills'].apply(len).describe()

Freelancer skills:

count    4372.000000
mean        8.136322
std         1.603356
min         2.000000
25%         8.000000
50%         8.000000
75%        10.000000
max        12.000000
Name: skills, dtype: float64

In [60]:
print(f"Workana categories:\n{df.loc[df['platform'] == 'Workana', 'category'].value_counts()}\n")
print(f"Freelancer categories:\n{df.loc[df['platform'] == 'Freelancer', 'category'].value_counts()}")

Workana categories:
category
Programación y Tecnología    350
Name: count, dtype: int64

Freelancer categories:
category
Websites, IT & Software    4222
Artificial Intelligence     150
Name: count, dtype: int64

In [57]:
df.loc[df['platform'] == 'Freelancer', 'category'].value_counts()

category
Websites, IT & Software    4222
Artificial Intelligence     150
Name: count, dtype: int64

## 8. Skills Analysis

In [78]:
rows = df['skills']

skills = []
for r in rows:
    skills.extend(r)

pd.Series(skills).value_counts()

PHP                             931
Graphic Design                  915
HTML                            812
Web Development                 642
Website Design                  636
                               ...
Automatic Speech Recognition      1
Seedance                          1
Machine Translation               1
Hebrew Translator                 1
Speech Synthesis                  1
Name: count, Length: 1542, dtype: int64

In [79]:
df['skills'].apply(len).describe()

count    4723.000000
mean        8.066483
std         1.781067
min         1.000000
25%         8.000000
50%         8.000000
75%         9.000000
max        23.000000
Name: skills, dtype: float64

## 9. Category Analysis

In [80]:
df['category'].value_counts()

category
Websites, IT & Software      4222
Programación y Tecnología     350
Artificial Intelligence       150
Name: count, dtype: int64

In [81]:
df['subcategory'].value_counts()

subcategory
Web Development                200
Programación Web               157
Adobe Premiere Pro             155
Adobe Illustrator              152
Web Design                     122
                              ...
Music Production                 1
Comedy Writing                   1
Architectural Visualization      1
Machine Translation              1
Email Handling                   1
Name: count, Length: 679, dtype: int64

In [86]:
print(f"Workana {df.loc[df['platform'] == 'Workana', 'subcategory'].value_counts()}\n")
print(f"Freelancer {df.loc[df['platform'] == 'Freelancer', 'subcategory'].value_counts()}")

Workana subcategory
Programación Web                              157
Inteligencia Artificial                        50
Tiendas Online (e-commerce)                    47
Programación de Apps. Android, iOS y otros     40
Aplicaciones de escritorio                     19
Otros                                          16
Wordpress                                      10
Data Science                                    9
Diseño Web                                      2
Name: count, dtype: int64

Freelancer subcategory
Web Development                200
Adobe Premiere Pro             155
Adobe Illustrator              152
Web Design                     122
Social Media Management         81
                              ...
Music Production                 1
Comedy Writing                   1
Architectural Visualization      1
Machine Translation              1
Email Handling                   1
Name: count, Length: 671, dtype: int64

## 10. Text Analysis

In [91]:
df['description'].apply(len).describe()

count    4723.00000
mean     1330.19585
std       908.11321
min        31.00000
25%       869.50000
50%      1187.00000
75%      1528.00000
max      9928.00000
Name: description, dtype: float64

There are multiple languages. It might be a challenge.

## 11. Target Variable Decision

For the first version of the model, only projects containing both `budget_min` and `budget_max` will be used. A new variable called `target_price` will be created as the midpoint of the budget range. Projects with open-ended budgets ("more than" or "less than") will be excluded from training.